import { Html, Head, Main, NextScript } from 'next/document'
export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href='../../code2-orange.svg' />
      </Head>
      <body>
        <Main />
        <NextScript />
        <div className='bg'/>
      </body>
    </Html>
  )
}
